"""
tag_versions.py — Retroactively apply agent_version to existing result and score files.

Assigns the correct pipeline version to every report that predates the versioning
system (introduced 2026-05-26). Safe to re-run — skips files that already carry
an agent_version field.

Version milestones are derived from the git commit history. Each version boundary
corresponds to a structural capability change (new data source, new agent pass,
new prompt architecture).

Usage:
    python .macro-assist/tag_versions.py
"""
from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path

RESULTS_DIR = Path(__file__).resolve().parent.parent / "results"
SCORES_DIR  = RESULTS_DIR / "scores"

# ---------------------------------------------------------------------------
# Version milestone date ranges (both bounds inclusive).
# A note dated on or after the start date of a milestone was generated by
# that version of the pipeline.
# ---------------------------------------------------------------------------
VERSION_MILESTONES: list[tuple[str, date, date]] = [
    ("v0.1", date(2026, 3, 12), date(2026, 4,  2)),  # Baseline: FRED + market data, signal matrix
    ("v0.2", date(2026, 4,  3), date(2026, 4,  4)),  # + Accuracy scoring, feedback loop
    ("v0.3", date(2026, 4,  5), date(2026, 4,  7)),  # + Opus, adversarial review, HY/ISM data
    ("v0.4", date(2026, 4,  8), date(2026, 4, 27)),  # + YouTube transcript integration
    ("v0.5", date(2026, 4, 28), date(2026, 5, 16)),  # + Portfolio positions (TR), Nasdaq data
    ("v0.6", date(2026, 5, 17), date(2026, 5, 18)),  # + Sector research, COT positioning
    ("v0.7", date(2026, 5, 19), date(2026, 5, 24)),  # + COT XLS fix, Pass 2 numerical anchoring
    ("v1.0", date(2026, 5, 25), date(2099, 12, 31)), # + Multi-agent: MA-1/MA-2/MA-3a
]


def version_for_date(d: date) -> str:
    for version, start, end in VERSION_MILESTONES:
        if start <= d <= end:
            return version
    return "unknown"


# ---------------------------------------------------------------------------
# Tag result markdown files
# ---------------------------------------------------------------------------

def tag_result_files() -> tuple[int, int]:
    """Insert agent_version into YAML frontmatter of all *-macro.md files.

    Inserts the field after the ``type: macro-intelligence`` line to match
    the format used by the pipeline going forward.

    Returns (tagged, skipped) counts.
    """
    tagged = skipped = 0
    for path in sorted(RESULTS_DIR.rglob("*-macro.md")):
        m = re.match(r"(\d{4}-\d{2}-\d{2})", path.name)
        if not m:
            continue
        report_date = date.fromisoformat(m.group(1))
        version = version_for_date(report_date)

        content = path.read_text(encoding="utf-8")
        if "agent_version:" in content:
            skipped += 1
            continue

        updated = re.sub(
            r"(^type: macro-intelligence\s*$)",
            r"\1\nagent_version: " + version,
            content,
            count=1,
            flags=re.MULTILINE,
        )
        if updated == content:
            print(f"  WARN: no 'type:' line found in {path.name} — skipping")
            skipped += 1
            continue

        path.write_text(updated, encoding="utf-8")
        tagged += 1
        print(f"  {path.name}  →  {version}")

    return tagged, skipped


# ---------------------------------------------------------------------------
# Tag score JSON files
# ---------------------------------------------------------------------------

def tag_score_files() -> tuple[int, int]:
    """Insert agent_version into results/scores/*.json files.

    The field is inserted immediately after report_date to keep the JSON
    readable in the same order as the markdown frontmatter.

    Returns (tagged, skipped) counts.
    """
    tagged = skipped = 0
    for path in sorted(SCORES_DIR.glob("*.json")):
        m = re.match(r"(\d{4}-\d{2}-\d{2})", path.stem)
        if not m:
            continue
        report_date = date.fromisoformat(m.group(1))
        version = version_for_date(report_date)

        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            print(f"  WARN: could not load {path.name}: {exc} — skipping")
            skipped += 1
            continue

        if "agent_version" in data:
            skipped += 1
            continue

        # Re-serialise with agent_version inserted after report_date
        new_data: dict = {}
        for k, v in data.items():
            new_data[k] = v
            if k == "report_date":
                new_data["agent_version"] = version

        path.write_text(json.dumps(new_data, indent=2), encoding="utf-8")
        tagged += 1
        print(f"  {path.name}  →  {version}")

    return tagged, skipped


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    print("=" * 55)
    print("tag_versions.py - backfilling agent_version metadata")
    print("=" * 55)

    print(f"\nTagging result markdown files in {RESULTS_DIR} ...")
    md_tagged, md_skipped = tag_result_files()
    print(f"  Result:  {md_tagged} tagged, {md_skipped} already had version / skipped\n")

    print(f"Tagging score JSON files in {SCORES_DIR} ...")
    j_tagged, j_skipped = tag_score_files()
    print(f"  Result:  {j_tagged} tagged, {j_skipped} already had version / skipped\n")

    print(f"Done. {md_tagged + j_tagged} file(s) updated.")
    print("\nNext step: re-run summarize_accuracy.py to regenerate")
    print("accuracy_summary.json with feedback_windows populated.")


if __name__ == "__main__":
    main()
